//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRRSystem.Models
{
    using System;
    using System.Data;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;
    
    public partial class HRRSEntities : DbContext
    {
        public HRRSEntities()
            : base("name=HRRSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }


        public void AddReservation(Reservation res)
        {
            string connectionString = @"data source=(LocalDB)\v11.0;attachdbfilename=|DataDirectory|\HRRS.mdf";
                //"data source=(LocalDB)\\v11.0;attachdbfilename=|DataDirectory|\\HRRS.mdf";
            //ConfigurationManager.ConnectionStrings["DBCS"].ConnectionString;
            try
            {
                using (SqlConnection con = new SqlConnection(connectionString))
                {
                    SqlCommand cmd = new SqlCommand("spAddReservation", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    SqlParameter paramName = new SqlParameter();
                    paramName.ParameterName = "@Name";
                    paramName.Value = res.name;
                    cmd.Parameters.Add(paramName);

                    SqlParameter paramCheck_in = new SqlParameter();
                    paramCheck_in.ParameterName = "@Check_in";
                    paramCheck_in.Value = res.check_in;
                    cmd.Parameters.Add(paramCheck_in);


                    SqlParameter paramCheck_out = new SqlParameter();
                    paramCheck_out.ParameterName = "@Check_out";
                    paramCheck_out.Value = res.check_in;
                    cmd.Parameters.Add(paramCheck_out);


                    SqlParameter paramRooms = new SqlParameter();
                    paramRooms.ParameterName = "@Rooms";
                    paramRooms.Value = res.rooms;
                    cmd.Parameters.Add(paramRooms);

                    SqlParameter paramNIC = new SqlParameter();
                    paramNIC.ParameterName = "@NIC";
                    paramNIC.Value = res.nic;
                    cmd.Parameters.Add(paramNIC);

                    SqlParameter paramAdults = new SqlParameter();
                    paramAdults.ParameterName = "@Adults";
                    paramAdults.Value = res.adults;
                    cmd.Parameters.Add(paramAdults);

                    con.Open();
                    cmd.ExecuteNonQuery();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }


        public void AddContacts(Contact contact)
        {
            try
            {
                string connectionString = @"data source=(LocalDB)\v11.0;attachdbfilename=|DataDirectory|\HRRS.mdf";
                //ConfigurationManager.ConnectionStrings["DBCS"].ConnectionString;

                using (SqlConnection con = new SqlConnection(connectionString))
                {
                    SqlCommand cmd = new SqlCommand("spAddContact", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    SqlParameter paramName = new SqlParameter();
                    paramName.ParameterName = "@Name";
                    paramName.Value = contact.name;
                    cmd.Parameters.Add(paramName);

                    SqlParameter paramEmail = new SqlParameter();
                    paramEmail.ParameterName = "@Email";
                    paramEmail.Value = contact.email;
                    cmd.Parameters.Add(paramEmail);

                    SqlParameter paramMobile = new SqlParameter();
                    paramMobile.ParameterName = "@Mobile";
                    paramMobile.Value = contact.mobile;
                    cmd.Parameters.Add(paramMobile);

                    SqlParameter paramSubject = new SqlParameter();
                    paramSubject.ParameterName = "@Subject";
                    paramSubject.Value = contact.consubject;
                    cmd.Parameters.Add(paramSubject);

                    con.Open();
                    cmd.ExecuteNonQuery();
                }
            }
            catch (SqlException e)
            {

            }
        }


    }


    
    }
