//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public string name { get; set; }
        public System.DateTime check_in { get; set; }
        public System.DateTime check_out { get; set; }
        public string rooms { get; set; }
        public string nic { get; set; }
        public int adults { get; set; }

       
    }

    public enum AdultsPerRoom
    {
        One,
        Two,
        Three,
        Four
    }

    public enum SelectRooms
    {
        SingleSuite,
        SingleRoom,
        DoubleRoom
    }
}
